import { Resume } from "@/types/resume";
import type { SectionConfig } from "@/components/builder/editor/GenericEntryEditor";

export const sectionConfigs: Record<string, SectionConfig> = {
  Projects: {
    dataKey: "projects",
    title: "Projects",
    description: "Showcase your best software projects, hacks, or contributions.",
    addLabel: "Add Project",
    fields: [
      { key: "title", label: "Project Title", type: "text", placeholder: "e.g. ResumeForge" },
      { key: "link", label: "Project Link (Optional)", type: "url", placeholder: "e.g. https://resumeforge.dev" },
      { key: "technologies", label: "Technologies (Comma-separated)", type: "tags", placeholder: "e.g. Next.js, FastAPI, PostgreSQL", spanFull: true },
    ],
    hasAIImprovement: true,
    improvementType: "project_bullet",
    improveLabel: "project title",
    createNew: () => ({
      id: "",
      enabled: true,
      title: "",
      link: "",
      technologies: [],
      bullets: [""],
    }),
    getEntries: (resume: Resume) => resume.projects || [],
    setEntries: (resume: Resume, entries: any[]) => ({ ...resume, projects: entries }),
    getEntryTitle: (entry: any) => entry.title || "",
    getEntrySubtitle: (entry: any) => (entry.technologies || []).join(", "),
  },

  Research: {
    dataKey: "research",
    title: "Research",
    description: "Highlight your academic research, publications, and scholarly work.",
    addLabel: "Add Research",
    fields: [
      { key: "title", label: "Research Title", type: "text", placeholder: "e.g. Machine Learning for NLP" },
      { key: "institution", label: "Institution / Organization", type: "text", placeholder: "e.g. Stanford University" },
      { key: "advisor", label: "Advisor (Optional)", type: "text", placeholder: "e.g. Dr. Jane Smith" },
      { key: "link", label: "Research Link (Optional)", type: "url", placeholder: "e.g. https://arxiv.org/abs/..." },
      { key: "duration", label: "Duration", type: "text", placeholder: "e.g. Jan 2024 - Present" },
      { key: "keywords", label: "Keywords (Comma-separated)", type: "tags", placeholder: "e.g. NLP, Transformers, BERT", spanFull: true },
    ],
    hasAIImprovement: false,
    createNew: () => ({
      id: "",
      enabled: true,
      title: "",
      institution: "",
      advisor: "",
      duration: "",
      link: "",
      keywords: [],
      bullets: [""],
    }),
    getEntries: (resume: Resume) => resume.research || [],
    setEntries: (resume: Resume, entries: any[]) => ({ ...resume, research: entries }),
    getEntryTitle: (entry: any) => entry.title || "",
    getEntrySubtitle: (entry: any) => entry.institution || "",
  },

  Publications: {
    dataKey: "publications",
    title: "Publications",
    description: "List your published papers, articles, and conference proceedings.",
    addLabel: "Add Publication",
    fields: [
      { key: "title", label: "Paper Title", type: "text", placeholder: "e.g. A Novel Approach to..." },
      { key: "authors", label: "Authors", type: "text", placeholder: "e.g. John Doe, Jane Smith" },
      { key: "venue", label: "Venue / Journal / Conference", type: "text", placeholder: "e.g. NeurIPS 2024" },
      { key: "doi", label: "DOI / URL (Optional)", type: "url", placeholder: "e.g. https://doi.org/10.xxxx/xxxxx" },
      { key: "date", label: "Publication Date", type: "text", placeholder: "e.g. Dec 2024" },
      { key: "keywords", label: "Keywords (Comma-separated)", type: "tags", placeholder: "e.g. Deep Learning, Computer Vision", spanFull: true },
      { key: "description", label: "Short Description (Optional)", type: "textarea-sm", placeholder: "Brief summary of the paper...", spanFull: true },
    ],
    hasAIImprovement: false,
    createNew: () => ({
      id: "",
      enabled: true,
      title: "",
      authors: "",
      venue: "",
      date: "",
      doi: "",
      keywords: [],
      description: "",
    }),
    getEntries: (resume: Resume) => resume.publications || [],
    setEntries: (resume: Resume, entries: any[]) => ({ ...resume, publications: entries }),
    getEntryTitle: (entry: any) => entry.title || "",
    getEntrySubtitle: (entry: any) => entry.venue || "",
  },
};
